
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Sprite : Luban.BeanBase
{
    public Sprite(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["AtlasId"].IsNumber) { throw new SerializationException(); }  AtlasId = _buf["AtlasId"]; }
    }

    public static Sprite DeserializeSprite(JSONNode _buf)
    {
        return new Sprite(_buf);
    }

    /// <summary>
    /// 图片名称
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 图集编号
    /// </summary>
    public readonly int AtlasId;
   
    public const int __ID__ = -1811812635;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "AtlasId:" + AtlasId + ","
        + "}";
    }
}
}

