
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SpriteAtlas : Luban.BeanBase
{
    public SpriteAtlas(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
    }

    public static SpriteAtlas DeserializeSpriteAtlas(JSONNode _buf)
    {
        return new SpriteAtlas(_buf);
    }

    /// <summary>
    /// 图集编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图集名称
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 1888677030;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "}";
    }
}
}

