
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.Tbitem Tbitem {get; }
    public TbSprite TbSprite {get; }
    public TbSpriteAtlas TbSpriteAtlas {get; }
    public TbTest TbTest {get; }
    public TbUIViewDefine TbUIViewDefine {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        TbSprite = new TbSprite(loader("tbsprite"));
        TbSpriteAtlas = new TbSpriteAtlas(loader("tbspriteatlas"));
        TbTest = new TbTest(loader("tbtest"));
        TbUIViewDefine = new TbUIViewDefine(loader("tbuiviewdefine"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbitem.ResolveRef(this);
        TbSprite.ResolveRef(this);
        TbSpriteAtlas.ResolveRef(this);
        TbTest.ResolveRef(this);
        TbUIViewDefine.ResolveRef(this);
    }
}

}
