
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbSprite
{
    private readonly System.Collections.Generic.Dictionary<string, Sprite> _dataMap;
    private readonly System.Collections.Generic.List<Sprite> _dataList;
    
    public TbSprite(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Sprite>(count);
        _dataList = new System.Collections.Generic.List<Sprite>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Sprite _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Sprite.DeserializeSprite(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Sprite> DataMap => _dataMap;
    public System.Collections.Generic.List<Sprite> DataList => _dataList;

    public Sprite GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Sprite Get(string key) => _dataMap[key];
    public Sprite this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

