
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbSpriteAtlas
{
    private readonly System.Collections.Generic.Dictionary<int, SpriteAtlas> _dataMap;
    private readonly System.Collections.Generic.List<SpriteAtlas> _dataList;
    
    public TbSpriteAtlas(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SpriteAtlas>(count);
        _dataList = new System.Collections.Generic.List<SpriteAtlas>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SpriteAtlas _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.SpriteAtlas.DeserializeSpriteAtlas(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SpriteAtlas> DataMap => _dataMap;
    public System.Collections.Generic.List<SpriteAtlas> DataList => _dataList;

    public SpriteAtlas GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SpriteAtlas Get(int key) => _dataMap[key];
    public SpriteAtlas this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

