
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbUIViewDefine
{
    private readonly System.Collections.Generic.Dictionary<string, UIViewDefine> _dataMap;
    private readonly System.Collections.Generic.List<UIViewDefine> _dataList;
    
    public TbUIViewDefine(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, UIViewDefine>(count);
        _dataList = new System.Collections.Generic.List<UIViewDefine>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UIViewDefine _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.UIViewDefine.DeserializeUIViewDefine(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, UIViewDefine> DataMap => _dataMap;
    public System.Collections.Generic.List<UIViewDefine> DataList => _dataList;

    public UIViewDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UIViewDefine Get(string key) => _dataMap[key];
    public UIViewDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

