
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class UIViewDefine : Luban.BeanBase
{
    public UIViewDefine(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _buf["AssetName"]; }
        { if(!_buf["UILayer"].IsNumber) { throw new SerializationException(); }  UILayer = _buf["UILayer"]; }
    }

    public static UIViewDefine DeserializeUIViewDefine(JSONNode _buf)
    {
        return new UIViewDefine(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 相对资源路径
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// ui层级（0. 底层UI（如场景背景） 1. 普通界面（如设置面板） 2. 弹窗（如确认框） 3. 顶层UI（如加载提示） 4. 系统级（如FPS显示））
    /// </summary>
    public readonly int UILayer;
   
    public const int __ID__ = -258642316;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "name:" + Name + ","
        + "AssetName:" + AssetName + ","
        + "UILayer:" + UILayer + ","
        + "}";
    }
}
}

